
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 17 21:15:06 CST 2022
//----------------------------------------------------

package jlexcompiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Or = 22;
  public static final int True = 24;
  public static final int Punto_y_coma = 5;
  public static final int Fi = 16;
  public static final int Until = 19;
  public static final int Coma = 10;
  public static final int If = 13;
  public static final int Potencia = 39;
  public static final int Comentario = 40;
  public static final int Else = 15;
  public static final int Read = 20;
  public static final int Then = 14;
  public static final int Diferente_que = 32;
  public static final int While = 17;
  public static final int Division = 36;
  public static final int Int = 6;
  public static final int Abre_llave = 3;
  public static final int Float = 7;
  public static final int Mayor_que = 28;
  public static final int EOF = 0;
  public static final int Abre_parentesis = 11;
  public static final int Not = 37;
  public static final int And = 23;
  public static final int error = 1;
  public static final int False = 25;
  public static final int Igual_que = 31;
  public static final int ERROR = 41;
  public static final int Do = 18;
  public static final int Cierra_llave = 4;
  public static final int Mayor_o_igual = 29;
  public static final int Cierra_parentesis = 12;
  public static final int Menor_que = 27;
  public static final int Identificador = 9;
  public static final int Resta = 34;
  public static final int Bool = 8;
  public static final int Multiplicacion = 35;
  public static final int Write = 21;
  public static final int Numero = 38;
  public static final int Program = 2;
  public static final int Suma = 33;
  public static final int Igual = 30;
  public static final int Menor_o_igual = 26;
}

